server:
  port: 9191


spring:
  application:
    # Application Name
    name: OAUTH2-SERVICE
#   DATABASE CONFIGURATIONS
  datasource:
    url: jdbc:mysql://localhost:3306/cogdb1?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: mynewpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

